# some stuff taken from SURF: http://code.google.com/p/surfrdf/source/browse/trunk/surf/namespace.py

# TO BE CLEANED UP


from rdflib import Namespace

ANNOTATION    = Namespace('http://www.w3.org/2000/10/annotation-ns#')
ANNOTEA       = Namespace('http://www.w3.org/2002/01/bookmark#')
ATOM          = Namespace('http://atomowl.org/ontologies/atomrdf#')
BIBO          = Namespace('http://purl.org/ontology/bibo/')
BIBO_DEGREES  = Namespace('http://purl.org/ontology/bibo/degrees/')
BIBO_EVENTS   = Namespace('http://purl.org/ontology/bibo/events/')
BIBO_ROLES    = Namespace('http://purl.org/ontology/bibo/roles/')
BIBO_STATUS   = Namespace('http://purl.org/ontology/bibo/status/')
CALENDAR      = Namespace('http://www.w3.org/2002/12/cal/icaltzd#')
CONTACT       = Namespace('http://www.w3.org/2000/10/swap/pim/contact#')
CORRIB_TAX    = Namespace('http://jonto.corrib.org/taxonomies#')
DBLP          = Namespace('http://www4.wiwiss.fu-berlin.de/dblp/terms.rdf#')
DBPEDIA       = Namespace('http://dbpedia.org/property/')
DC            = Namespace('http://purl.org/dc/elements/1.1/')
DCTERMS       = Namespace('http://purl.org/dc/terms/')
DOAP          = Namespace('http://usefulinc.com/ns/doap#')
EVENT         = Namespace('http://purl.org/NET/c4dm/event.owl#')
EXIF          = Namespace('http://www.w3.org/2003/12/exif/ns/')
FOAF          = Namespace('http://xmlns.com/foaf/0.1/')
FRBR          = Namespace('http://purl.org/vocab/frbr/core#')
FRESNEL       = Namespace('http://www.w3.org/2004/09/fresnel#')
FTI           = Namespace('http://franz.com/ns/allegrograph/2.2/textindex/')
GEO           = Namespace('http://www.w3.org/2003/01/geo/wgs84_pos#')
GR            = Namespace('http://purl.org/goodrelations/v1#')
IBIS          = Namespace('http://purl.org/ibis#')
IDEAS         = Namespace('http://protege.stanford.edu/rdf')
IMDB          = Namespace('http://www.csd.abdn.ac.uk/~ggrimnes/dev/imdb/IMDB#')
JDL_STRUCTURE = Namespace('http://www.jeromedl.org/structure#')
JONTO_DDC     = Namespace('http://www.corrib.org/jonto/ddc#')
JONTO_PKT     = Namespace('http://www.corrib.org/jonto/pkt#')
LUBM          = Namespace('http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#')
MARCONT       = Namespace('http://www.marcont.org/ontology#')
MO            = Namespace('http://purl.org/ontology/mo/')
OWL           = Namespace('http://www.w3.org/2002/07/owl#')
PIM           = Namespace('http://www.w3.org/2000/10/swap/pim/contact#')
RESUME        = Namespace('http://captsolo.net/semweb/resume/cv.rdfs#')
REVIEW        = Namespace('http://www.isi.edu/webscripter/communityreview/abstract-review-o#')
SERENITY3     = Namespace('http://serenity.deri.org/imdb#')
SIOC          = Namespace('http://rdfs.org/sioc/ns#')
SIOC_SERVICES = Namespace('http://rdfs.org/sioc/services#')
SIOC_TYPES    = Namespace('http://rdfs.org/sioc/types#')
SKOS          = Namespace('http://www.w3.org/2004/02/skos/core#')
SURF          = Namespace('http://code.google.com/p/surfrdf/')
TIME          = Namespace('http://www.w3.org/2006/time#')
VANN          = Namespace('http://purl.org/vocab/vann/')
VCARD         = Namespace('http://nwalsh.com/rdf/vCard#')
VS            = Namespace('http://www.w3.org/2003/06/sw-vocab-status/ns#')
WGS84_POS     = Namespace('http://www.w3.org/2003/01/geo/wgs84_pos#')
WIKIONT       = Namespace('http://sw.deri.org/2005/04/wikipedia/wikiont.owl')
WORDNET       = Namespace('http://xmlns.com/wordnet/1.6/')
WOT           = Namespace('http://xmlns.com/wot/0.1/')
XFOAF         = Namespace('http://www.foafrealm.org/xfoaf/0.1/')
XMLNS         = Namespace('http://www.w3.org/XML/1998/namespace')
XSD           = Namespace("http://www.w3.org/2001/XMLSchema#")
YAGO          = Namespace('http://dbpedia.org/class/yago/')